version: "2"

services:
  auca-judge-queue:
    build: "."
    image: "toksaitov/auca-judge-queue"
    depends_on:
      - "auca-judge-etcd-db"
      - "auca-judge-redis-db"
      - "auca-judge-mongo-db"

  auca-judge-etcd-db:
    image: "quay.io/coreos/etcd:v2.3.3"
    networks:
      default:
        aliases:
          - "auca-judge-discovery-db"
  auca-judge-redis-db:
    image: "redis:3.0.7"
    networks:
      default:
        aliases:
          - "auca-judge-queue-db"
  auca-judge-mongo-db:
    image: "mongo:3.2.6"
    networks:
      default:
        aliases:
          - "auca-judge-task-db"
